const students = [
    {
      _id: '1',
      name: 'XYZ',
      image: '/images/students/xyz.png',
      email: 'xyz@email.com',
      rollNumber: 1,
      position: 'BTech',
      areasOfInterest: 'in machine learning',
      thesisTitle: 'Stars',
      description: 'hey stars ..hh df dljf',
      scholarLink: 'www.link.com',
      linkedin: 'https://www.linkedin.com/in/gupta-rajan/',
      alumni: 'Yes',
      alumniPosition: 'Manager',
      publications: 'Reference',
    },
    {
      _id: '2',
      name: 'ABC',
      image: '/images/students/abc.png',
      email: 'abc@email.com',
      rollNumber: 2,
      position: 'MTech',
      areasOfInterest: 'in artificial intelligence',
      thesisTitle: 'Galaxies',
      description: 'hello galaxies ..jd dfo jfe',
      scholarLink: 'www.link2.com',
      linkedin: 'www.linkedin2.com',
      alumni: 'No',
      alumniPosition: '',
      publications: 'None',
    },
    {
      _id: '3',
      name: 'PQR',
      image: '/images/students/pqr.png',
      email: 'pqr@email.com',
      rollNumber: 3,
      position: 'PhD',
      areasOfInterest: 'in computer vision',
      thesisTitle: 'Planets',
      description: 'greetings planets ..df dlkf sd',
      scholarLink: 'www.link3.com',
      linkedin: 'www.linkedin3.com',
      alumni: 'Yes',
      alumniPosition: 'Researcher',
      publications: 'Journal of Space Exploration',
    },
    {
      _id: '4',
      name: 'LMN',
      image: '/images/lmn.png',
      email: 'lmn@email.com',
      rollNumber: 4,
      position: 'BTech',
      areasOfInterest: 'in robotics',
      thesisTitle: 'Asteroids',
      description: 'hello asteroids ..er sdfo jlk',
      scholarLink: 'www.link4.com',
      linkedin: 'www.linkedin4.com',
      alumni: 'No',
      alumniPosition: '',
      publications: 'Robotics Conference Proceedings',
    },
    // Add more students as needed
    // ...
  ];
  
  export default students;
  